version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
        network:
            ipv4_address: 172.28.1.1
volumes:
  db:
    driver: local

networks:
    network:
        ipam:
            driver: default
            config:
            - subnet: 172.28.0.0/16
